# Generated by Django 4.2.5 on 2023-10-09 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flatpages.flatpage')),
            ],
        ),
    ]
