# Generated by Django 4.2.5 on 2023-10-09 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Meister', '0002_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
        migrations.AddField(
            model_name='entry',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entry',
            name='categories',
            field=models.ManyToManyField(to='Meister.category'),
        ),
        migrations.AddField(
            model_name='entry',
            name='enable_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='status',
            field=models.IntegerField(choices=[(1, 'Live'), (2, 'Draft'), (3, 'Hidden')], default=1),
        ),
    ]
