# Generated by Django 4.2.5 on 2023-10-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meister', '0003_alter_entry_options_entry_author_entry_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='body_html',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='excerpt_html',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='excerpt',
            field=models.TextField(blank=True, help_text='A short summary of the entry, Optional'),
        ),
    ]
