# Generated by Django 4.2.5 on 2023-10-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meister', '0004_entry_body_html_entry_excerpt_html_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
