# Generated by Django 4.2.6 on 2023-11-02 07:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9)),
                ('year_of_graduation', models.IntegerField(default=2023)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('RegistrationNumber', models.CharField(help_text='Registration Number', max_length=9)),
                ('picture', models.ImageField(upload_to='student_images')),
                ('firstname', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('middlename', models.CharField(blank=True, max_length=32)),
                ('state_of_orign', models.CharField(max_length=32)),
                ('DateOfBirth', models.DateField(default=datetime.datetime.now)),
                ('Set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.class')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssessmentScore', models.IntegerField(default=0)),
                ('ExamScore', models.IntegerField(default=0)),
                ('student_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='SchoolApp.studentresult')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='SchoolApp.course')),
                ('teacherInCharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
