# Generated by Django 4.2.6 on 2023-11-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='term',
            field=models.CharField(choices=[('FIRST TERM', 'FIRST TERM'), ('SECOND TERM', 'SECOND TERM'), ('THIRD TERM', 'THIRD TERM')], default=1, max_length=32),
            preserve_default=False,
        ),
    ]
