# Generated by Django 4.2.5 on 2024-01-03 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Subject'},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Year_Of_Graduation',
            new_name='Class',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.level'),
        ),
    ]
