# Generated by Django 4.2.5 on 2024-01-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0002_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
