# Generated by Django 4.2.6 on 2023-11-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0002_studentresult_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='Position',
            field=models.IntegerField(default=100, max_length=32),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='RemarkFromPrincipal',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='RemarkFromTeacher',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='average',
            field=models.IntegerField(default=100, max_length=32),
        ),
    ]
