# Generated by Django 4.2.6 on 2023-11-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0003_studentresult_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='Position',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='RemarkFromPrincipal',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='RemarkFromTeacher',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='average',
            field=models.IntegerField(default=100),
        ),
    ]
