# Generated by Django 4.2.6 on 2023-11-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0004_alter_studentresult_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='RemarkFromPrincipal',
            field=models.CharField(default='', max_length=100),
        ),
    ]
