# Generated by Django 4.2.5 on 2024-01-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0006_alter_result_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='average',
            field=models.FloatField(default=100),
        ),
    ]
