# Generated by Django 4.2.6 on 2023-11-02 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0007_alter_studentresult_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='RegistrationNumber',
            field=models.CharField(help_text='Registration Number', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='teacherInCharge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.teacher'),
        ),
    ]
