# Generated by Django 4.2.5 on 2023-11-04 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0010_alter_student_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='state_of_orign',
            new_name='state_of_origin',
        ),
    ]
