# Generated by Django 4.2.5 on 2023-11-10 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0011_rename_state_of_orign_student_state_of_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='SchoolApp.student'),
        ),
    ]
