# Generated by Django 4.2.5 on 2023-12-14 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0015_schooldata_session_current'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='school_data')),
                ('Data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.schooldata')),
            ],
        ),
    ]
