# Generated by Django 4.2.5 on 2023-12-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0017_alter_schoolimage_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldata',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
