# Generated by Django 4.2.5 on 2023-12-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0018_schooldata_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldata',
            name='excerpt',
            field=models.TextField(default='', editable=False, max_length=500),
        ),
    ]
