# Generated by Django 4.2.5 on 2023-12-29 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0019_schooldata_excerpt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Set',
            new_name='Year_Of_Graduation',
        ),
    ]
